dist: trusty

language: node_js

node_js:
  - lts/*

before_script:
  - rm -rf docs || exit 0

install:
  - yarn

script:
  - yarn build

cache: yarn

deploy:
  - provider: pages
    local-dir: docs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  # - provider: npm
  #   email: <your_email>
  #   # api_key: travis encrypt NPM_TOKEN --add deploy.api_key --com
  #   on:
  #     branch: master
  #   skip-cleanup: true
